site_name: R4Pi.org
repo_url: https://github.com/r4pi/r4pi.org
docs_dir: content
site_dir: docs
theme: 
  name: simplex
nav:
  - installation.md
  - using_r.md
  - Learning R:
    - tutorials/index.md
    - tutorials/further_reading.md
extra_css:
  - css/extra.css
