site_name: R4Pi.org
repo_url: https://github.com/r4pi/r4pi.org
edit_uri: blob/main/content
docs_dir: content
site_dir: docs
theme: 
  name: simplex
nav:
  - installation.md
  - using_r.md
  - tutorials/further_reading.md
extra_css:
  - css/extra.css
