site_name: R4Pi.org
repo_url: https://github.com/r4pi/r4pi.org
edit_uri: blob/main/content
docs_dir: content
site_dir: docs
theme: 
  name: simplex
nav:
  - Documentation:
    - docs/installation.md
    - docs/using_r.md
    - docs/install_packages.md
    - docs/ide.md
  - tutorials/further_reading.md
extra_css:
  - css/extra.css
